version: "3.9"
services:
  loki:
    image: grafana/loki:2.9.6
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki/local-config.yaml"]
  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=7d
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:10.4.3
    depends_on:
      - loki
      - prometheus
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage:


